# Generated by Django 4.0.3 on 2022-07-29 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repos', '0003_organization_save_repository'),
        ('services', '0002_deployment_is_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repos.repository'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
