# Generated by Django 4.0.3 on 2022-07-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_deployment_repository_deployment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='github_created',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='github_updated',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
