# Generated by Django 4.0.3 on 2022-07-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='save_repository',
            field=models.BooleanField(default=False),
        ),
    ]
