# Generated by Django 4.0.3 on 2022-07-31 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0004_githubstate_githubevent_raw_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GithubState',
        ),
    ]
