# Generated by Django 4.0.3 on 2022-07-31 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0005_delete_githubstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='num_events_scanned',
            field=models.IntegerField(default=0, help_text='Number of times the events have been scanned'),
        ),
    ]
